// Last updated: 9/26/2026, 2:41:57 PM


    
import java.util.*;

class Solution {
   public List<String> braceExpansionII(String expression) {
            Set<String> result = parse(expression, new int[]{0});
                    List<String> ans = new ArrayList<>(result);
                            Collections.sort(ans);
                                    return ans;
                                        }

                                            private Set<String> parse(String s, int[] index) {
                                                    Set<String> result = new HashSet<>();
                                                            Set<String> current = new HashSet<>();
                                                                    current.add("");

                                                                            while (index[0] < s.length() && s.charAt(index[0]) != '}') {
                                                                                        char ch = s.charAt(index[0]);

                                                                                                    if (ch == ',') {
                                                                                                                    result.addAll(current);
                                                                                                                                    current = new HashSet<>();
                                                                                                                                                    current.add("");
                                                                                                                                                                    index[0]++;
                                                                                                                                                                                } else {
                                                                                                                                                                                                Set<String> part;

                                                                                                                                                                                                                if (ch == '{') {
                                                                                                                                                                                                                                    index[0]++;
                                                                                                                                                                                                                                                        part = parse(s, index);
                                                                                                                                                                                                                                                                            index[0]++;
                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                part = new HashSet<>();
                                                                                                                                                                                                                                                                                                                                    part.add(String.valueOf(ch));
                                                                                                                                                                                                                                                                                                                                                        index[0]++;
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                        current = combine(current, part);
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                    result.addAll(current);
                                                                                                                                                                                                                                                                                                                                                                                                                            return result;
                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                    private Set<String> combine(Set<String> a, Set<String> b) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            Set<String> result = new HashSet<>();

                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (String x : a) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (String y : b) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                result.add(x + y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return result;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }